import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@component/styles/Home.module.css";
import gsap from "gsap";
import { useEffect } from "react";
import { CustomEase } from "gsap/dist/CustomEase";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  gsap.registerPlugin(CustomEase);
  useEffect(() => {
    gsap.fromTo(
      ".fact1",
      {
        left: "-15%",
        duration: 1,
        opacity: 0,
      },
      { left: "5%", opacity: 1, duration: 4, delay: 2.5 }
    );

    gsap.fromTo(
      ".fact2",
      {
        left: "150%",
        duration: 1,
        opacity: 0,
      },
      { left: "80%", opacity: 1, duration: 4, delay: 5.5 }
    );

    gsap.fromTo(
      ".fact3",
      {
        left: "-15%",
        duration: 1,
        opacity: 0,
      },
      { left: "5%", opacity: 1, duration: 4, delay: 7.5 }
    );

    gsap.fromTo(
      ".fact4",
      {
        left: "150%",
        duration: 1,
        opacity: 0,
      },
      { left: "80%", opacity: 1, duration: 4, delay: 9.5 }
    );

    gsap.fromTo(
      ".headline",
      {
        opacity: 0,
        duration: 2,
        ease: "power4.out",
      },
      {
        opacity: 1,
        duration: 2,
        ease: CustomEase.create(
          "custom",
          "M0,0 C0.14,0 0.172,0.453 0.202,0.576 0.243,0.743 0.312,0.771 0.32,0.808 0.328,0.793 0.414,0.873 0.455,0.811 0.51,0.726 0.571,0.639 0.584,0.648 0.66,0.698 0.667,0.883 0.674,0.9 0.736,0.816 0.763,0.72 0.782,0.734 0.801,0.748 0.87,0.933 0.884,0.946 0.895,0.942 0.919,0.86 0.934,0.86 0.949,0.86 1,1 1,1"
        ),
        yoyo: true,
        repeat: 2,
      }
    );

    gsap.fromTo(
      ".overlay",
      {
        opacity: 1,
        duration: 1,
      },
      {
        delay: 2,
        opacity: 0,
        duration: 2,
      }
    );
  }, []);

  return (
    <>
      <Head>
        <title>Branche kendskab</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={`${styles.headline} headline `}>Fisker Ocean</h1>
        <div className={`${styles.overlay} overlay `}></div>
        <p className={`${styles.fact1} fact1 `}>
          Rækkevidde: <br /> Op til 630 km¹
        </p>
        <p className={`${styles.fact2} fact2 `}>0-100 km/h på 3,9s </p>
        <p className={`${styles.fact3} fact3 `}>
          Fuldstændig elektrisk. <br /> Dynamisk. <br /> Førerfokuseret.
        </p>
        <p className={`${styles.fact4} fact4 `}>
          Uovertruffen <br /> parkeringsteknologi
        </p>
      </main>
    </>
  );
}
